version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: dealbot-admin
      POSTGRES_USER: admin
      POSTGRES_DB: dealbot
  controller:
    build: ..
    command: ["controller", "--listen", ":8764", "--metrics", "prometheus", "--driver", "postgres", "--dbloc", "postgresql://admin:dealbot-admin@db:5432/dealbot?sslmode=disable"]
    ports:
      - "8764:8764"
    depends_on: 
      - db
    environment: 
      - VIRTUAL_HOST=localhost
  mockbot:
    build: ..
    command: ["mock", "--endpoint", "http://controller:8764"]
    depends_on: 
      - controller
    environment:
      - MOCK_DEALBOT_WORKERS
      - MOCK_DEALBOT_SUCCESS_RATE
      - MOCK_DEALBOT_SUCCESS_AVG
      - MOCK_DEALBOT_SUCCESS_DEVIATION
      - MOCK_DEALBOT_FAILURE_AVG
      - MOCK_DEALBOT_FAILURE_DEVIATION
  metrics:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on: 
      - controller
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - "./htpasswd:/etc/nginx/htpasswd"
      - "./vhost:/etc/nginx/vhost.d"
